name: Cypress Tests

on: [push]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          spec: 'cypress/e2e/apiTests.cy.js'
          record: false
          start: npx cypress run --env name=dev

      - name: Upload Reports as Artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: cypress-reports
          path: cypress/reports/*.html
