name: Cypress Tests

on: [push]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          spec: 'cypress/e2e/apiTests.cy.js'
          record: false
          start: npx cypress run --env name='dev'

      - name: Merge and Generate Report
        if: ${{ always() }}
        run: |
          npx mochawesome-merge cypress/reports/*.json -o cypress/reports/merged-report.json
          npx mochawesome-report-generator cypress/reports/merged-report.json
        continue-on-error: true

      - name: Upload Reports as Artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: cypress-reports
          path: cypress/reports/
